// https://stackoverflow.com/questions/64032166/tailwindcss-not-working-with-next-js-what-is-wrong-with-the-configuration

import "../globals.css";
import Header from "./header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <section>
        {/* Include shared UI here e.g. a header or sidebar */}
        <nav>
            <Header></Header>
        </nav>
   
        {children}
      </section>
        
        </body>
    </html>
  )
}
